### ISSUE TITLE
Releases for submodules soanydata, cpack.d

### ISSUE THREAD

**Issue by looooo** [coin3d/soqt#54]
To build soqt, it's necessary to have sources of sogui, soanydata, cpack.d available. While sogui is available as version 1.4.0 I am missing releases for soanydata and cpack.d. Would it be possible to create these releases?

**Comment by looooo** [comment]
Also I think the cpack-submodule shouldn't be mandatory and should be disabled by default:
- https://github.com/coin3d/soqt/pull/55
- https://github.com/coin3d/simage/pull/31

**Comment by lepalom** [comment]
I think that it could be useful if you make a release of the corresponding submodules of soqt in the way that a SoQt release with its modules. In my case I'm be able to execute uscan to obtain the necessary sources to build the debian package.

**Comment by hobbes1069** [comment]
Just found the github move. GOOD!

Ok, so I worked around the git submodules in a very ugly way for Fedora but it works (documented at the bottom). However, I'm not sure how easy this is to do but what should really happen is the official release archives should already have the submodules included. Period. That's the point of providing release archives. It should be complete.

To make updates manageable in the spec file I put this in the header:
```
%global cpack_hash 118ac5a21bcf57f0f90e2b0e681c9dcbf07074c2
%global cpack_short %(c=%{cpack_hash}; echo ${c:0:10})
%global cpack_date 20200419
%global soanydata_hash 3ff6e9203fbb0cc08a2bdf209212b7ef4d78a1f2
%global soanydata_short %(c=%{soanydata_hash}; echo ${c:0:10})
%global soanydata_date 20200419
%global sogui_hash 4b0019d1ecc2b9ad3e77333b9f243b57a15ebc4e
%global sogui_short %(c=%{soanydata_hash}; echo ${c:0:10})
%global sogui_date 20200419
```
The sources later in the spec file:
```
Source1:        https://github.com/coin3d/cpack.d/archive/%{cpack_hash}/coin3d-cpack-%{cpack_date}git%{cpack_short}.tar.gz
Source2:        https://github.com/coin3d/soanydata/archive/%{soanydata_hash}/coin3d-soanydata-%{soanydata_date}git%{soanydata_short}.tar.gz
Source3:        https://github.com/coin3d/sogui/archive/%{sogui_hash}/coin3d-sogui-%{sogui_date}git%{sogui_short}.tar.gz
```
And then unpack them in %prep:
```
mkdir cpack.d data src/Inventor/Qt/common
tar --strip-components=1 -C cpack.d -xf %{SOURCE1}
tar --strip-components=1 -C data -xf %{SOURCE2}
tar --strip-components=1 -C src/Inventor/Qt/common -xf %{SOURCE3}
```

**Comment by VolkerEnderlein** [comment]
The releases of coin 4.0.0, soqt 1.6.0, sowin 1.6.0, soxt 1.4.0, simage 1.8.0, superglu 1.3.0, simvoleon 2.1.0, dime 0.9.1, profit 0.9.1, and smallchange 1.0.0 have been populated on the Coin3D GitHub repository with fully functional source tarballs and zip files that include sogui, soanydata, and cpack.d. SHA256 and MD5 files are also in place.
Additionally releases for sogui (tags soxt-1_4_0, soqt-1_6_0, soqt-1_6_0) cpack.d (tag cpack.d-1_0_0) and soanydata (tag soanydata-1_1_0) have been done. Hope that helps for the package maintainers.

**Comment by hobbes1069** [comment]
Ok, github still does the automated archives at the bottom, so I just need to use the uploaded archive, correct?

**Comment by VolkerEnderlein** [comment]
Exactly. I cannot make those links disappear :(

**Comment by hobbes1069** [comment]
No worries, I know better now. Doesn't look like I can close the issue though.

**Comment by VolkerEnderlein** [comment]
@looooo Do you think we can close this issue?

**Comment by looooo** [comment]
Yes, if pulling all the submodules is not be necessary anymore. I haven't tried yet.
https://github.com/conda-forge/soqt-feedstock/blob/master/recipe/meta.yaml#L16L25

**Comment by VolkerEnderlein** [comment]
The archives are created automatically by GitHub and therefore do not contain the submodules up to now. I provided separate source tarballs in the releases including the submodules that can be downloaded from: 
https://github.com/coin3d/superglu/releases/download/superglu-1.3.0/superglu-1.3.0-src.tar.gz
https://github.com/coin3d/coin/releases/download/Coin-4.0.0/coin-4.0.0-src.tar.gz
https://github.com/coin3d/soqt/releases/download/SoQt-1.6.0/soqt-1.6.0-src.tar.gz
https://github.com/coin3d/simage/releases/download/simage-1.8.0/simage-1.8.0-src.tar.gz
There are zip files and SHA256 and MD5 checksum files as well for those packages.

**Comment by looooo** [comment]
perfect, thanks, I will try to remember.
