### ISSUE TITLE
New release for qt6 support

### ISSUE THREAD

**Issue by looooo** [coin3d/soqt#74]
Is it possible to have a new release for qt6 support?

**Comment by VolkerEnderlein** [comment]
Done. I've done some checks but I would ask you @looooo kindly to test the 4.0.1 and 1.6.1 bugfix releases.

**Comment by looooo** [comment]
thanks @VolkerEnderlein I wasn't yet able to test the new version a lot. Just a few things that came up:
for windows: it was not possible to simply replace coin4.0.0 with coin4.0.1. A rebuild of pivy and freecad is necessary. For the other platforms this is not necessary.

ref: https://forum.freecad.org/viewtopic.php?t=82952

**Comment by VolkerEnderlein** [comment]
That sounds like we lost binary compatibility with version 4.0.0. It is not intended. I'll have a closer look on it over the next few days.
