### ISSUE TITLE
Qt6.5.2 Soqt1.dll issue

### ISSUE THREAD

**Issue by canbilal1995** [coin3d/soqt#77]
I am using coin4.dll v4.0.0 and soqt msvc16 x64bit windows v1.6.1 for qt 6.5
After a successful compilation of the project, I tried to open executable file generated and it prompts an error like below.
![image](https://github.com/coin3d/soqt/assets/26367476/534c796b-803b-4fca-a641-fbe1c3965f5b)
I have put the soqt1.dll into the same directory with the .exe file.

Previously I was using qt5.15 with soqt 1.6.0 and there was no problem. I migrated my qt project to qt6.5.2 and updated soqt to 1.6.1 for the compatibility but this .dll error comes up. I need a solution to fix the problem. 

dependency walker result:
![image](https://github.com/coin3d/soqt/assets/26367476/32885926-b89e-4ade-8dd5-06430b797329)

**Comment by VolkerEnderlein** [comment]
Thanks for the report. Lately we had an issue with Coin 4.0.1 not being binary compatible with Coin 4.0.0. Unfortunatly the binaries for SoQt 1.6.1 links against coin 4.0.1. Can you try to use the SoQt1.dll binaries from the CI builds section? They use the latest coin version that fixes this issue.

**Comment by canbilal1995** [comment]
Should I also upgrade Coin 4.0.0 to 4.0.1? I only installed the CI build of soqt now and currently executables are working

**Comment by canbilal1995** [comment]
As I understood, CI build is not a official release for you. When will it be released?

**Comment by VolkerEnderlein** [comment]
You are right, the CI builds are only snapshots of the current development, but are consistent over all Coin3D repositories. So when building SoQt latest, we use Coin latest, superglu latest, and so on. To test whether a problem still persists, it is sometimes advisable to use the CI builds. But if you want to release a version of your software you should always bind to the latest released versions of Coin and SoQt.

We released Coin v4.0.2 to reestablish binary compatibility with Coin v4.0.0. So when upgrading you should choose v4.0.2 together with SoQt. I will release a patch version of SoQt over the next days that binds correctly to Coin v4.0.2.

**Comment by VolkerEnderlein** [comment]
Done. I explicitely checked whether an Examiner viewer from SoQt 1.6.2 release can be run with Coin v4.0.0 and Coin v4.0.2.
